// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC75xhhfi9mk6lNVkrs8st_btE2oJ8eOCk',
    appId: '1:436639168127:web:b03c0ca805ed8d7216314a',
    messagingSenderId: '436639168127',
    projectId: 'unityaidhub',
    authDomain: 'unityaidhub.firebaseapp.com',
    storageBucket: 'unityaidhub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS2oIz32lmZ3BMQjbuWGdC2LlsdGpzLT4',
    appId: '1:436639168127:android:d1a055a48c5943b016314a',
    messagingSenderId: '436639168127',
    projectId: 'unityaidhub',
    storageBucket: 'unityaidhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2sRpKgHE6usd-BJDRMHfdlqQlNDFvzFM',
    appId: '1:436639168127:ios:e79b5abd0f8d648916314a',
    messagingSenderId: '436639168127',
    projectId: 'unityaidhub',
    storageBucket: 'unityaidhub.appspot.com',
    iosBundleId: 'com.example.unityAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2sRpKgHE6usd-BJDRMHfdlqQlNDFvzFM',
    appId: '1:436639168127:ios:0cae07e6b2a563a016314a',
    messagingSenderId: '436639168127',
    projectId: 'unityaidhub',
    storageBucket: 'unityaidhub.appspot.com',
    iosBundleId: 'com.example.unityAdmin.RunnerTests',
  );
}
